spring:
  jpa:
    database: MYSQL
    hibernate:
      format-sql: true
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/bd_xml
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
